version: '3'
services:
  spring-boot-app:
    build:
      context: ./CCTV
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - flask-app

  flask-app:
    build:
      context: ./flask-app
      dockerfile: Dockerfile
    ports:
      - "5001:5000"
